import {
	IDataObject,
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	NodeApiError,
	NodeConnectionType,
} from 'n8n-workflow';

export class Serper implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Google Search API',
		name: 'serper',
		icon: 'file:serper.svg',
		group: ['transform'],
		version: 1,
		subtitle: '={{ $parameter["resource"] + " - " + $parameter["operation"] }}',
		description:
			'Integrate with Google Search API (Serper.dev API) for search functionalities. Powered by CloudFly',
		defaults: { name: 'Serper' },
		inputs: [NodeConnectionType.Main],
		outputs: [NodeConnectionType.Main],
		credentials: [{ name: 'serperApi', required: true }],
		properties: [
			// Resources
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{ name: 'Image', value: 'images' },
					{ name: 'News', value: 'news' },
					{ name: 'Scholar', value: 'schollar' },
					{ name: 'Search', value: 'search' },
					{ name: 'Shopping', value: 'shopping' },
					{ name: 'Video', value: 'videos' },
				],
				default: 'search',
			},
			// Operations for each Resource
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['search'] } },
				options: [
					{
						name: 'Web Search',
						value: 'webSearch',
						description: 'Basic web search',
						action: 'Perform a web search',
					},
				],
				default: 'webSearch',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['images'] } },
				options: [
					{
						name: 'Search Images',
						value: 'searchImages',
						description: 'Search for images',
						action: 'Search images',
					},
					{
						name: 'Image Search (Lens)',
						value: 'imageSearchLens',
						description: 'Reverse image search with Lens',
						action: 'Image search lens',
					},
				],
				default: 'searchImages',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['videos'] } },
				options: [
					{
						name: 'Find Videos',
						value: 'findVideos',
						description: 'Search for videos',
						action: 'Find videos',
					},
				],
				default: 'findVideos',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['news'] } },
				options: [
					{
						name: 'Find News',
						value: 'findNews',
						description: 'Search for news articles',
						action: 'Find news',
					},
				],
				default: 'findNews',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['shopping'] } },
				options: [
					{
						name: 'Shopping Search',
						value: 'shoppingSearch',
						description: 'Search for products',
						action: 'Shopping search',
					},
				],
				default: 'shoppingSearch',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: { show: { resource: ['schollar'] } },
				options: [
					{
						name: 'Scholar Search',
						value: 'scholarSearch',
						description: 'Search for scholarly articles',
						action: 'Scholar search',
					},
				],
				default: 'scholarSearch',
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				description: 'Page number for paginated results',
				displayOptions: {
					show: {
						resource: ['search', 'images', 'videos', 'news', 'shopping', 'schollar'],
					},
					hide: {
						operation: ['imageSearchLens'],
					},
				},
			},
			{
				displayName: 'Query',
				name: 'query',
				type: 'string',
				required: true,
				default: '',
				description: 'The search query for the action',
				displayOptions: {
					show: {
						resource: ['search', 'images', 'videos', 'news', 'shopping', 'schollar'],
					},
					hide: {
						operation: ['imageSearchLens'],
					},
				},
			},
			{
				displayName: 'Results',
				name: 'num',
				type: 'options',
				options: [
					{ name: '10', value: 10 },
					{ name: '20', value: 20 },
					{ name: '40', value: 40 },
					{ name: '60', value: 60 },
					{ name: '80', value: 80 },
					{ name: '100', value: 100 },
				],
				default: 40,
				description: 'Number of results to return',
				displayOptions: {
					show: {
						resource: ['search', 'images', 'videos', 'news', 'shopping', 'schollar'],
					},
					hide: {
						operation: ['imageSearchLens'],
					},
				},
			},
			// Image-specific field for Lens operation
			{
				displayName: 'Image URL',
				name: 'url',
				type: 'string',
				default: '',
				placeholder: 'Image URL for reverse search',
				description: 'URL of the image for reverse search',
				required: true,
				displayOptions: {
					show: {
						resource: ['images'],
						operation: ['imageSearchLens'],
					},
				},
			},
			// Common Fields
			{
				displayName: 'Country',
				name: 'gl',
				type: 'options',
				options: [
					{ name: '🇦🇩 Andorra (Ad)', value: 'ad' },
					{ name: '🇦🇪 United Arab Emirates (Ae)', value: 'ae' },
					{ name: '🇦🇫 Afghanistan (Af)', value: 'af' },
					{ name: '🇦🇬 Antigua and Barbuda (Ag)', value: 'ag' },
					{ name: '🇦🇮 Anguilla (Ai)', value: 'ai' },
					{ name: '🇦🇱 Albania (Al)', value: 'al' },
					{ name: '🇦🇲 Armenia (Am)', value: 'am' },
					{ name: '🇦🇳 Netherlands Antilles (An)', value: 'an' },
					{ name: '🇦🇴 Angola (Ao)', value: 'ao' },
					{ name: '🇦🇶 Antarctica (Aq)', value: 'aq' },
					{ name: '🇦🇷 Argentina (Ar)', value: 'ar' },
					{ name: '🇦🇸 American Samoa (As)', value: 'as' },
					{ name: '🇦🇹 Austria (At)', value: 'at' },
					{ name: '🇦🇺 Australia (Au)', value: 'au' },
					{ name: '🇦🇼 Aruba (Aw)', value: 'aw' },
					{ name: '🇦🇿 Azerbaijan (Az)', value: 'az' },
					{ name: '🇧🇦 Bosnia and Herzegovina (Ba)', value: 'ba' },
					{ name: '🇧🇧 Barbados (Bb)', value: 'bb' },
					{ name: '🇧🇩 Bangladesh (Bd)', value: 'bd' },
					{ name: '🇧🇪 Belgium (Be)', value: 'be' },
					{ name: '🇧🇫 Burkina Faso (Bf)', value: 'bf' },
					{ name: '🇧🇬 Bulgaria (Bg)', value: 'bg' },
					{ name: '🇧🇭 Bahrain (Bh)', value: 'bh' },
					{ name: '🇧🇮 Burundi (Bi)', value: 'bi' },
					{ name: '🇧🇯 Benin (Bj)', value: 'bj' },
					{ name: '🇧🇲 Bermuda (Bm)', value: 'bm' },
					{ name: '🇧🇳 Brunei Darussalam (Bn)', value: 'bn' },
					{ name: '🇧🇴 Bolivia (Bo)', value: 'bo' },
					{ name: '🇧🇷 Brazil (Br)', value: 'br' },
					{ name: '🇧🇸 Bahamas (Bs)', value: 'bs' },
					{ name: '🇧🇹 Bhutan (Bt)', value: 'bt' },
					{ name: '🇧🇻 Bouvet Island (Bv)', value: 'bv' },
					{ name: '🇧🇼 Botswana (Bw)', value: 'bw' },
					{ name: '🇧🇾 Belarus (By)', value: 'by' },
					{ name: '🇨🇦 Canada (Ca)', value: 'ca' },
					{ name: '🇨🇨 Cocos (Keeling) Islands (Cc)', value: 'cc' },
					{ name: '🇨🇩 Congo, the Democratic Republic of the (Cd)', value: 'cd' },
					{ name: '🇨🇫 Central African Republic (Cf)', value: 'cf' },
					{ name: '🇨🇬 Congo (Cg)', value: 'cg' },
					{ name: '🇨🇭 Switzerland (Ch)', value: 'ch' },
					{ name: "🇨🇮 Cote D'ivoire (Ci)", value: 'ci' },
					{ name: '🇨🇰 Cook Islands (Ck)', value: 'ck' },
					{ name: '🇨🇱 Chile (Cl)', value: 'cl' },
					{ name: '🇨🇲 Cameroon (Cm)', value: 'cm' },
					{ name: '🇨🇳 China (Cn)', value: 'cn' },
					{ name: '🇨🇴 Colombia (Co)', value: 'co' },
					{ name: '🇨🇷 Costa Rica (Cr)', value: 'cr' },
					{ name: '🇨🇻 Cape Verde (Cv)', value: 'cv' },
					{ name: '🇨🇽 Christmas Island (Cx)', value: 'cx' },
					{ name: '🇨🇾 Cyprus (Cy)', value: 'cy' },
					{ name: '🇨🇿 Czech Republic (Cz)', value: 'cz' },
					{ name: '🇩🇪 Germany (De)', value: 'de' },
					{ name: '🇩🇯 Djibouti (Dj)', value: 'dj' },
					{ name: '🇩🇰 Denmark (Dk)', value: 'dk' },
					{ name: '🇩🇲 Dominica (Dm)', value: 'dm' },
					{ name: '🇩🇴 Dominican Republic (Do)', value: 'do' },
					{ name: '🇩🇿 Algeria (Dz)', value: 'dz' },
					{ name: '🇪🇨 Ecuador (Ec)', value: 'ec' },
					{ name: '🇪🇪 Estonia (Ee)', value: 'ee' },
					{ name: '🇪🇬 Egypt (Eg)', value: 'eg' },
					{ name: '🇪🇭 Western Sahara (Eh)', value: 'eh' },
					{ name: '🇪🇷 Eritrea (Er)', value: 'er' },
					{ name: '🇪🇸 Spain (Es)', value: 'es' },
					{ name: '🇪🇹 Ethiopia (Et)', value: 'et' },
					{ name: '🇫🇮 Finland (Fi)', value: 'fi' },
					{ name: '🇫🇯 Fiji (Fj)', value: 'fj' },
					{ name: '🇫🇰 Falkland Islands (Malvinas) (Fk)', value: 'fk' },
					{ name: '🇫🇲 Micronesia, Federated States of (Fm)', value: 'fm' },
					{ name: '🇫🇴 Faroe Islands (Fo)', value: 'fo' },
					{ name: '🇫🇷 France (Fr)', value: 'fr' },
					{ name: '🇬🇦 Gabon (Ga)', value: 'ga' },
					{ name: '🇬🇧 United Kingdom (Gb)', value: 'gb' },
					{ name: '🇬🇩 Grenada (Gd)', value: 'gd' },
					{ name: '🇬🇪 Georgia (Ge)', value: 'ge' },
					{ name: '🇬🇫 French Guiana (Gf)', value: 'gf' },
					{ name: '🇬🇭 Ghana (Gh)', value: 'gh' },
					{ name: '🇬🇮 Gibraltar (Gi)', value: 'gi' },
					{ name: '🇬🇱 Greenland (Gl)', value: 'gl' },
					{ name: '🇬🇲 Gambia (Gm)', value: 'gm' },
					{ name: '🇬🇳 Guinea (Gn)', value: 'gn' },
					{ name: '🇬🇵 Guadeloupe (Gp)', value: 'gp' },
					{ name: '🇬🇶 Equatorial Guinea (Gq)', value: 'gq' },
					{ name: '🇬🇷 Greece (Gr)', value: 'gr' },
					{ name: '🇬🇸 South Georgia and the South Sandwich Islands (Gs)', value: 'gs' },
					{ name: '🇬🇹 Guatemala (Gt)', value: 'gt' },
					{ name: '🇬🇺 Guam (Gu)', value: 'gu' },
					{ name: '🇬🇼 Guinea-Bissau (Gw)', value: 'gw' },
					{ name: '🇬🇾 Guyana (Gy)', value: 'gy' },
					{ name: '🇭🇰 Hong Kong (Hk)', value: 'hk' },
					{ name: '🇭🇲 Heard Island and Mcdonald Islands (Hm)', value: 'hm' },
					{ name: '🇭🇳 Honduras (Hn)', value: 'hn' },
					{ name: '🇭🇷 Croatia (Hr)', value: 'hr' },
					{ name: '🇭🇹 Haiti (Ht)', value: 'ht' },
					{ name: '🇭🇺 Hungary (Hu)', value: 'hu' },
					{ name: '🇮🇩 Indonesia (ID)', value: 'id' },
					{ name: '🇮🇪 Ireland (Ie)', value: 'ie' },
					{ name: '🇮🇱 Israel (Il)', value: 'il' },
					{ name: '🇮🇳 India (In)', value: 'in' },
					{ name: '🇮🇴 British Indian Ocean Territory (Io)', value: 'io' },
					{ name: '🇮🇶 Iraq (Iq)', value: 'iq' },
					{ name: '🇮🇷 Iran, Islamic Republic of (Ir)', value: 'ir' },
					{ name: '🇮🇸 Iceland (Is)', value: 'is' },
					{ name: '🇮🇹 Italy (It)', value: 'it' },
					{ name: '🇯🇲 Jamaica (Jm)', value: 'jm' },
					{ name: '🇯🇴 Jordan (Jo)', value: 'jo' },
					{ name: '🇯🇵 Japan (Jp)', value: 'jp' },
					{ name: '🇰🇪 Kenya (Ke)', value: 'ke' },
					{ name: '🇰🇬 Kyrgyzstan (Kg)', value: 'kg' },
					{ name: '🇰🇭 Cambodia (Kh)', value: 'kh' },
					{ name: '🇰🇮 Kiribati (Ki)', value: 'ki' },
					{ name: '🇰🇲 Comoros (Km)', value: 'km' },
					{ name: '🇰🇳 Saint Kitts and Nevis (Kn)', value: 'kn' },
					{ name: "🇰🇵 Korea, Democratic People's Republic of (Kp)", value: 'kp' },
					{ name: '🇰🇷 Korea, Republic of (Kr)', value: 'kr' },
					{ name: '🇰🇼 Kuwait (Kw)', value: 'kw' },
					{ name: '🇰🇾 Cayman Islands (Ky)', value: 'ky' },
					{ name: '🇰🇿 Kazakhstan (Kz)', value: 'kz' },
					{ name: "🇱🇦 Lao People's Democratic Republic (La)", value: 'la' },
					{ name: '🇱🇧 Lebanon (Lb)', value: 'lb' },
					{ name: '🇱🇨 Saint Lucia (Lc)', value: 'lc' },
					{ name: '🇱🇮 Liechtenstein (Li)', value: 'li' },
					{ name: '🇱🇰 Sri Lanka (Lk)', value: 'lk' },
					{ name: '🇱🇷 Liberia (Lr)', value: 'lr' },
					{ name: '🇱🇸 Lesotho (Ls)', value: 'ls' },
					{ name: '🇱🇹 Lithuania (Lt)', value: 'lt' },
					{ name: '🇱🇺 Luxembourg (Lu)', value: 'lu' },
					{ name: '🇱🇻 Latvia (Lv)', value: 'lv' },
					{ name: '🇱🇾 Libyan Arab Jamahiriya (Ly)', value: 'ly' },
					{ name: '🇲🇦 Morocco (Ma)', value: 'ma' },
					{ name: '🇲🇨 Monaco (Mc)', value: 'mc' },
					{ name: '🇲🇩 Moldova, Republic of (Md)', value: 'md' },
					{ name: '🇲🇬 Madagascar (Mg)', value: 'mg' },
					{ name: '🇲🇭 Marshall Islands (Mh)', value: 'mh' },
					{ name: '🇲🇰 Macedonia, the Former Yugosalv Republic of (Mk)', value: 'mk' },
					{ name: '🇲🇱 Mali (Ml)', value: 'ml' },
					{ name: '🇲🇲 Myanmar (Mm)', value: 'mm' },
					{ name: '🇲🇳 Mongolia (Mn)', value: 'mn' },
					{ name: '🇲🇴 Macao (Mo)', value: 'mo' },
					{ name: '🇲🇵 Northern Mariana Islands (Mp)', value: 'mp' },
					{ name: '🇲🇶 Martinique (Mq)', value: 'mq' },
					{ name: '🇲🇷 Mauritania (Mr)', value: 'mr' },
					{ name: '🇲🇸 Montserrat (Ms)', value: 'ms' },
					{ name: '🇲🇹 Malta (Mt)', value: 'mt' },
					{ name: '🇲🇺 Mauritius (Mu)', value: 'mu' },
					{ name: '🇲🇻 Maldives (Mv)', value: 'mv' },
					{ name: '🇲🇼 Malawi (Mw)', value: 'mw' },
					{ name: '🇲🇽 Mexico (Mx)', value: 'mx' },
					{ name: '🇲🇾 Malaysia (My)', value: 'my' },
					{ name: '🇲🇿 Mozambique (Mz)', value: 'mz' },
					{ name: '🇳🇦 Namibia (Na)', value: 'na' },
					{ name: '🇳🇨 New Caledonia (Nc)', value: 'nc' },
					{ name: '🇳🇪 Niger (Ne)', value: 'ne' },
					{ name: '🇳🇫 Norfolk Island (Nf)', value: 'nf' },
					{ name: '🇳🇬 Nigeria (Ng)', value: 'ng' },
					{ name: '🇳🇮 Nicaragua (Ni)', value: 'ni' },
					{ name: '🇳🇱 Netherlands (Nl)', value: 'nl' },
					{ name: '🇳🇴 Norway (No)', value: 'no' },
					{ name: '🇳🇵 Nepal (Np)', value: 'np' },
					{ name: '🇳🇷 Nauru (Nr)', value: 'nr' },
					{ name: '🇳🇺 Niue (Nu)', value: 'nu' },
					{ name: '🇳🇿 New Zealand (Nz)', value: 'nz' },
					{ name: '🇴🇲 Oman (Om)', value: 'om' },
					{ name: '🇵🇦 Panama (Pa)', value: 'pa' },
					{ name: '🇵🇪 Peru (Pe)', value: 'pe' },
					{ name: '🇵🇫 French Polynesia (Pf)', value: 'pf' },
					{ name: '🇵🇬 Papua New Guinea (Pg)', value: 'pg' },
					{ name: '🇵🇭 Philippines (Ph)', value: 'ph' },
					{ name: '🇵🇰 Pakistan (Pk)', value: 'pk' },
					{ name: '🇵🇱 Poland (Pl)', value: 'pl' },
					{ name: '🇵🇲 Saint Pierre and Miquelon (Pm)', value: 'pm' },
					{ name: '🇵🇳 Pitcairn (Pn)', value: 'pn' },
					{ name: '🇵🇷 Puerto Rico (Pr)', value: 'pr' },
					{ name: '🇵🇸 Palestinian Territory, Occupied (Ps)', value: 'ps' },
					{ name: '🇵🇹 Portugal (Pt)', value: 'pt' },
					{ name: '🇵🇼 Palau (Pw)', value: 'pw' },
					{ name: '🇵🇾 Paraguay (Py)', value: 'py' },
					{ name: '🇶🇦 Qatar (Qa)', value: 'qa' },
					{ name: '🇷🇪 Reunion (Re)', value: 're' },
					{ name: '🇷🇴 Romania (Ro)', value: 'ro' },
					{ name: '🇷🇸 Serbia and Montenegro (Rs)', value: 'rs' },
					{ name: '🇷🇺 Russian Federation (Ru)', value: 'ru' },
					{ name: '🇷🇼 Rwanda (Rw)', value: 'rw' },
					{ name: '🇸🇦 Saudi Arabia (Sa)', value: 'sa' },
					{ name: '🇸🇧 Solomon Islands (Sb)', value: 'sb' },
					{ name: '🇸🇨 Seychelles (Sc)', value: 'sc' },
					{ name: '🇸🇩 Sudan (Sd)', value: 'sd' },
					{ name: '🇸🇪 Sweden (Se)', value: 'se' },
					{ name: '🇸🇬 Singapore (Sg)', value: 'sg' },
					{ name: '🇸🇭 Saint Helena (Sh)', value: 'sh' },
					{ name: '🇸🇮 Slovenia (Si)', value: 'si' },
					{ name: '🇸🇯 Svalbard and Jan Mayen (Sj)', value: 'sj' },
					{ name: '🇸🇰 Slovakia (Sk)', value: 'sk' },
					{ name: '🇸🇱 Sierra Leone (Sl)', value: 'sl' },
					{ name: '🇸🇲 San Marino (Sm)', value: 'sm' },
					{ name: '🇸🇳 Senegal (Sn)', value: 'sn' },
					{ name: '🇸🇴 Somalia (So)', value: 'so' },
					{ name: '🇸🇷 Suriname (Sr)', value: 'sr' },
					{ name: '🇸🇹 Sao Tome and Principe (St)', value: 'st' },
					{ name: '🇸🇻 El Salvador (Sv)', value: 'sv' },
					{ name: '🇸🇾 Syrian Arab Republic (Sy)', value: 'sy' },
					{ name: '🇸🇿 Swaziland (Sz)', value: 'sz' },
					{ name: '🇹🇨 Turks and Caicos Islands (Tc)', value: 'tc' },
					{ name: '🇹🇩 Chad (Td)', value: 'td' },
					{ name: '🇹🇫 French Southern Territories (Tf)', value: 'tf' },
					{ name: '🇹🇬 Togo (Tg)', value: 'tg' },
					{ name: '🇹🇭 Thailand (Th)', value: 'th' },
					{ name: '🇹🇯 Tajikistan (Tj)', value: 'tj' },
					{ name: '🇹🇰 Tokelau (Tk)', value: 'tk' },
					{ name: '🇹🇱 Timor-Leste (Tl)', value: 'tl' },
					{ name: '🇹🇲 Turkmenistan (Tm)', value: 'tm' },
					{ name: '🇹🇳 Tunisia (Tn)', value: 'tn' },
					{ name: '🇹🇴 Tonga (To)', value: 'to' },
					{ name: '🇹🇷 Turkey (Tr)', value: 'tr' },
					{ name: '🇹🇹 Trinidad and Tobago (Tt)', value: 'tt' },
					{ name: '🇹🇻 Tuvalu (Tv)', value: 'tv' },
					{ name: '🇹🇼 Taiwan, Province of China (Tw)', value: 'tw' },
					{ name: '🇹🇿 Tanzania, United Republic of (Tz)', value: 'tz' },
					{ name: '🇺🇦 Ukraine (Ua)', value: 'ua' },
					{ name: '🇺🇬 Uganda (Ug)', value: 'ug' },
					{ name: '🇺🇲 United States Minor Outlying Islands (Um)', value: 'um' },
					{ name: '🇺🇸 United States (Us)', value: 'us' },
					{ name: '🇺🇾 Uruguay (Uy)', value: 'uy' },
					{ name: '🇺🇿 Uzbekistan (Uz)', value: 'uz' },
					{ name: '🇻🇦 Holy See (Vatican City State) (Va)', value: 'va' },
					{ name: '🇻🇨 Saint Vincent and the Grenadines (Vc)', value: 'vc' },
					{ name: '🇻🇪 Venezuela (Ve)', value: 've' },
					{ name: '🇻🇬 Virgin Islands, British (Vg)', value: 'vg' },
					{ name: '🇻🇮 Virgin Islands, U.S. (Vi)', value: 'vi' },
					{ name: '🇻🇳 Viet Nam (Vn)', value: 'vn' },
					{ name: '🇻🇺 Vanuatu (Vu)', value: 'vu' },
					{ name: '🇼🇫 Wallis and Futuna (Wf)', value: 'wf' },
					{ name: '🇼🇸 Samoa (Ws)', value: 'ws' },
					{ name: '🇾🇪 Yemen (Ye)', value: 'ye' },
					{ name: '🇾🇹 Mayotte (Yt)', value: 'yt' },
					{ name: '🇿🇦 South Africa (Za)', value: 'za' },
					{ name: '🇿🇲 Zambia (Zm)', value: 'zm' },
					{ name: '🇿🇼 Zimbabwe (Zw)', value: 'zw' },
				],
				default: 'us',
				description: 'Country code for search',
				displayOptions: {
					show: {
						resource: ['search', 'images', 'videos', 'news', 'shopping', 'schollar'],
					},
				},
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'options',
				options: [
					{ name: 'Acholi (Ach)', value: 'ach' },
					{ name: 'Afrikaans (Af)', value: 'af' },
					{ name: 'Akan (Ak)', value: 'ak' },
					{ name: 'Albanian (Sq)', value: 'sq' },
					{ name: 'Amharic (Am)', value: 'am' },
					{ name: 'Arabic (Ar)', value: 'ar' },
					{ name: 'Armenian (Hy)', value: 'hy' },
					{ name: 'Azerbaijani (Az)', value: 'az' },
					{ name: 'Basque (Eu)', value: 'eu' },
					{ name: 'Belarusian (Be)', value: 'be' },
					{ name: 'Bemba (Bem)', value: 'bem' },
					{ name: 'Bengali (Bn)', value: 'bn' },
					{ name: 'Bihari (Bh)', value: 'bh' },
					{ name: 'Bork, Bork, Bork! (Xx-Bork)', value: 'xx-bork' },
					{ name: 'Bosnian (Bs)', value: 'bs' },
					{ name: 'Breton (Br)', value: 'br' },
					{ name: 'Bulgarian (Bg)', value: 'bg' },
					{ name: 'Cambodian (Km)', value: 'km' },
					{ name: 'Catalan (Ca)', value: 'ca' },
					{ name: 'Cherokee (Chr)', value: 'chr' },
					{ name: 'Chichewa (Ny)', value: 'ny' },
					{ name: 'Chinese (Simplified) (Zh-Cn)', value: 'zh-cn' },
					{ name: 'Chinese (Traditional) (Zh-Tw)', value: 'zh-tw' },
					{ name: 'Corsican (Co)', value: 'co' },
					{ name: 'Croatian (Hr)', value: 'hr' },
					{ name: 'Czech (Cs)', value: 'cs' },
					{ name: 'Danish (Da)', value: 'da' },
					{ name: 'Dutch (Nl)', value: 'nl' },
					{ name: 'Elmer Fudd (Xx-Elmer )', value: 'xx-elmer' },
					{ name: 'English (En)', value: 'en' },
					{ name: 'Esperanto (Eo)', value: 'eo' },
					{ name: 'Estonian (Et)', value: 'et' },
					{ name: 'Ewe (Ee)', value: 'ee' },
					{ name: 'Faroese (Fo)', value: 'fo' },
					{ name: 'Filipino (Tl)', value: 'tl' },
					{ name: 'Finnish (Fi)', value: 'fi' },
					{ name: 'French (Fr)', value: 'fr' },
					{ name: 'Frisian (Fy)', value: 'fy' },
					{ name: 'Ga (Gaa)', value: 'gaa' },
					{ name: 'Galician (Gl)', value: 'gl' },
					{ name: 'Georgian (Ka)', value: 'ka' },
					{ name: 'German (De)', value: 'de' },
					{ name: 'Greek (El)', value: 'el' },
					{ name: 'Guarani (Gn)', value: 'gn' },
					{ name: 'Gujarati (Gu)', value: 'gu' },
					{ name: 'Hacker (Xx-Hacker )', value: 'xx-hacker' },
					{ name: 'Haitian Creole (Ht)', value: 'ht' },
					{ name: 'Hausa (Ha)', value: 'ha' },
					{ name: 'Hawaiian (Haw)', value: 'haw' },
					{ name: 'Hebrew (Iw)', value: 'iw' },
					{ name: 'Hindi (Hi)', value: 'hi' },
					{ name: 'Hungarian (Hu)', value: 'hu' },
					{ name: 'Icelandic (Is)', value: 'is' },
					{ name: 'Igbo (Ig)', value: 'ig' },
					{ name: 'Indonesian (ID)', value: 'id' },
					{ name: 'Interlingua (Ia)', value: 'ia' },
					{ name: 'Irish (Ga)', value: 'ga' },
					{ name: 'Italian (It)', value: 'it' },
					{ name: 'Japanese (Ja)', value: 'ja' },
					{ name: 'Javanese (Jw)', value: 'jw' },
					{ name: 'Kannada (Kn)', value: 'kn' },
					{ name: 'Kazakh (Kk)', value: 'kk' },
					{ name: 'Kinyarwanda (Rw)', value: 'rw' },
					{ name: 'Kirundi (Rn)', value: 'rn' },
					{ name: 'Klingon (Xx-Klingon)', value: 'xx-klingon' },
					{ name: 'Kongo (Kg)', value: 'kg' },
					{ name: 'Korean (Ko)', value: 'ko' },
					{ name: 'Krio (Sierra Leone) (Kri)', value: 'kri' },
					{ name: 'Kurdish (Ku)', value: 'ku' },
					{ name: 'Kurdish (Soranî) (Ckb)', value: 'ckb' },
					{ name: 'Kyrgyz (Ky)', value: 'ky' },
					{ name: 'Laothian (Lo)', value: 'lo' },
					{ name: 'Latin (La)', value: 'la' },
					{ name: 'Latvian (Lv)', value: 'lv' },
					{ name: 'Lingala (Ln)', value: 'ln' },
					{ name: 'Lithuanian (Lt)', value: 'lt' },
					{ name: 'Lozi (Loz)', value: 'loz' },
					{ name: 'Luganda (Lg)', value: 'lg' },
					{ name: 'Macedonian (Mk)', value: 'mk' },
					{ name: 'Malagasy (Mg)', value: 'mg' },
					{ name: 'Malay (Ms)', value: 'ms' },
					{ name: 'Malayalam (Ml)', value: 'ml' },
					{ name: 'Maltese (Mt)', value: 'mt' },
					{ name: 'Maori (Mi)', value: 'mi' },
					{ name: 'Marathi (Mr)', value: 'mr' },
					{ name: 'Mauritian Creole (Mfe)', value: 'mfe' },
					{ name: 'Moldavian (Mo)', value: 'mo' },
					{ name: 'Mongolian (Mn)', value: 'mn' },
					{ name: 'Montenegrin (Sr-ME)', value: 'sr-ME' },
					{ name: 'Nepali (Ne)', value: 'ne' },
					{ name: 'Nigerian Pidgin (Pcm)', value: 'pcm' },
					{ name: 'Northern Sotho (Nso)', value: 'nso' },
					{ name: 'Norwegian (No)', value: 'no' },
					{ name: 'Norwegian (Nynorsk) (Nn)', value: 'nn' },
					{ name: 'Occitan (Oc)', value: 'oc' },
					{ name: 'Oriya (Or)', value: 'or' },
					{ name: 'Oromo (Om)', value: 'om' },
					{ name: 'Pashto (Ps)', value: 'ps' },
					{ name: 'Persian (Fa)', value: 'fa' },
					{ name: 'Pirate (Xx-Pirate)', value: 'xx-pirate' },
					{ name: 'Polish (Pl)', value: 'pl' },
					{ name: 'Portuguese (Brazil) (Pt-Br)', value: 'pt-br' },
					{ name: 'Portuguese (Portugal) (Pt-Pt)', value: 'pt-pt' },
					{ name: 'Portuguese (Pt)', value: 'pt' },
					{ name: 'Punjabi (Pa)', value: 'pa' },
					{ name: 'Quechua (Qu)', value: 'qu' },
					{ name: 'Romanian (Ro)', value: 'ro' },
					{ name: 'Romansh (Rm)', value: 'rm' },
					{ name: 'Runyakitara (Nyn)', value: 'nyn' },
					{ name: 'Russian (Ru)', value: 'ru' },
					{ name: 'Scots Gaelic (Gd)', value: 'gd' },
					{ name: 'Serbian (Sr)', value: 'sr' },
					{ name: 'Serbo-Croatian (Sh)', value: 'sh' },
					{ name: 'Sesotho (St)', value: 'st' },
					{ name: 'Setswana (Tn)', value: 'tn' },
					{ name: 'Seychellois Creole (Crs)', value: 'crs' },
					{ name: 'Shona (Sn)', value: 'sn' },
					{ name: 'Sindhi (Sd)', value: 'sd' },
					{ name: 'Sinhalese (Si)', value: 'si' },
					{ name: 'Slovak (Sk)', value: 'sk' },
					{ name: 'Slovenian (Sl)', value: 'sl' },
					{ name: 'Somali (So)', value: 'so' },
					{ name: 'Spanish (Es)', value: 'es' },
					{ name: 'Spanish (Latin American) (Es-419)', value: 'es-419' },
					{ name: 'Sundanese (Su)', value: 'su' },
					{ name: 'Swahili (Sw)', value: 'sw' },
					{ name: 'Swedish (Sv)', value: 'sv' },
					{ name: 'Tajik (Tg)', value: 'tg' },
					{ name: 'Tamil (Ta)', value: 'ta' },
					{ name: 'Tatar (Tt)', value: 'tt' },
					{ name: 'Telugu (Te)', value: 'te' },
					{ name: 'Thai (Th)', value: 'th' },
					{ name: 'Tigrinya (Ti)', value: 'ti' },
					{ name: 'Tonga (To)', value: 'to' },
					{ name: 'Tshiluba (Lua)', value: 'lua' },
					{ name: 'Tumbuka (Tum)', value: 'tum' },
					{ name: 'Turkish (Tr)', value: 'tr' },
					{ name: 'Turkmen (Tk)', value: 'tk' },
					{ name: 'Twi (Tw)', value: 'tw' },
					{ name: 'Uighur (Ug)', value: 'ug' },
					{ name: 'Ukrainian (Uk)', value: 'uk' },
					{ name: 'Urdu (Ur)', value: 'ur' },
					{ name: 'Uzbek (Uz)', value: 'uz' },
					{ name: 'Vietnamese (Vi)', value: 'vi' },
					{ name: 'Welsh (Cy)', value: 'cy' },
					{ name: 'Wolof (Wo)', value: 'wo' },
					{ name: 'Xhosa (Xh)', value: 'xh' },
					{ name: 'Yiddish (Yi)', value: 'yi' },
					{ name: 'Yoruba (Yo)', value: 'yo' },
					{ name: 'Zulu (Zu)', value: 'zu' },
				],
				default: 'en',
				description: 'Language code for search',
				displayOptions: {
					show: {
						resource: ['search', 'images', 'videos', 'news', 'shopping', 'schollar'],
					},
				},
			},
			{
				displayName: 'Autocorrect',
				name: 'autocorrect',
				type: 'boolean',
				default: true,
				description: 'Whether to enable autocorrect',
				displayOptions: {
					show: {
						resource: ['search', 'images', 'videos', 'news', 'shopping', 'schollar'],
					},
					hide: {
						operation: ['imageSearchLens'],
					},
				},
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const returnData: INodeExecutionData[] = [];
		const baseUrl = 'https://google.serper.dev/';

		for (let i = 0; i < items.length; i++) {
			try {
				const resource = this.getNodeParameter('resource', i) as string;
				const operation = this.getNodeParameter('operation', i) as string;
				const query = this.getNodeParameter('query', i) as string;

				let endpoint = resource; // e.g., 'search', 'images', etc.
				const body: IDataObject = { q: query };

				// Add common params
				body.gl = this.getNodeParameter('gl', i) as string;
				body.hl = this.getNodeParameter('hl', i) as string;
				body.autocorrect = this.getNodeParameter('autocorrect', i) as boolean;
				body.page = this.getNodeParameter('page', i) as number;
				body.num = this.getNodeParameter('num', i) as number;

				// Handle specific operations
				if (resource === 'images' && operation === 'imageSearchLens') {
					body.url = this.getNodeParameter('url', i) as string;
					endpoint = 'lens'; // Adjust if Serper has specific endpoint for Lens
				}

				const response = await this.helpers.httpRequestWithAuthentication.call(this, 'serperApi', {
					method: 'POST',
					url: `${baseUrl}${endpoint}`,
					body,
					json: true,
				});

				const executionData = this.helpers.constructExecutionMetaData(
					this.helpers.returnJsonArray(response as IDataObject),
					{ itemData: { item: i } },
				);

				returnData.push(...executionData);
			} catch (error) {
				if (this.continueOnFail()) {
					const executionData = this.helpers.constructExecutionMetaData(
						this.helpers.returnJsonArray({ error: error.message } as IDataObject),
						{ itemData: { item: i } },
					);
					returnData.push(...executionData);
					continue;
				}
				throw new NodeApiError(this.getNode(), error);
			}
		}
		return [returnData];
	}
}
